#!/bin/bash

if [[ `whoami` != "root" ]]; then
    echo "You are not root. You should be."
    exit 1
fi

deleted="`dpkg -l | grep ^rc | cut -d" " -f 3`"

if [[ -z $deleted ]]; then
    echo "Nothing to purge."
    exit 0
fi

echo "The following packages have been deleted, but not purged:"
echo $deleted

while :; do
    read -p "Do you want to purge them? [Y/n] " response
    case "`echo $response | awk '{print tolower($0)}'`" in
	y|yes)
            for i in $deleted; do
		dpkg -P "$i"
	    done
	    break
	    ;;
	n|no)
	    break
	    ;;
    esac
done
